In [213]:
#importación de modulos
import  requests
from tqdm import tqdm   #por probarlo, es un modulo que crea una barra de progreso para cualquier proceso
import pandas as pd
from bs4 import BeautifulSoup

## Scraping Tesla Quarterly revenue

In [214]:
#url del sitio a scrapear
url = " https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"

#headers definidos para evitar errores en el request
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"}

#efectuamos el request del codigo html
response = requests.get(url, headers=headers)
#definimos un condicional para manejar errores de importación
if response.status_code != 200:
    print('error al conectar')
#convertimos la respuesta a texto
response_html = response.text

In [216]:
#creamos el objeto soup 
soup = bs.BeautifulSoup(response_html, 'html.parser')
#buscamos todos los elementos de la clase 'table'
tablas = soup.findAll(class_ = 'table')
#selecciono el indice 1 de la lista 'tablas' que se corresponde con lo que busco
tablas_Tesla_Quarterly = tablas[1]
#extraigo todas las filas de la lista
filas = tablas_Tesla_Quarterly.tbody.findAll('tr')

#defino dos variables para almacenar los datos de las filas
valores = []
fechas = []
#Iteramos sobre cada una de las filas para extraer los valores de las columnas 'fecha' y 'valor'
for tr in filas:
    columna = tr.findAll('td')
    fecha = columna[0].text
    valor = columna[1].text
    fechas.append(fecha)
    valores.append(valor)

#creamos una variable para almacenar los valores numericos limpios    
valores_limpios = []
#iteramos sobre la lista valores para eliminar espacios, simbolos y convertir a entero
for valor in valores:
    valor_limpio = valor.replace('$', '')
    valor_limpio = valor_limpio.replace(',', '').strip()
    #comprobamos que el valor existe y lo añadimos a la lista
    if valor_limpio:
        valores_limpios.append(int(valor_limpio))
    else:
        valores_limpios.append(None)
        
#creamos el dataframe
df = pd.DataFrame({'fecha': fechas, 'valor': valores_limpios})
df

         fecha    valor
0   2023-12-31  25167.0
1   2023-09-30  23350.0
2   2023-06-30  24927.0
3   2023-03-31  23329.0
4   2022-12-31  24318.0
5   2022-09-30  21454.0
6   2022-06-30  16934.0
7   2022-03-31  18756.0
8   2021-12-31  17719.0
9   2021-09-30  13757.0
10  2021-06-30  11958.0
11  2021-03-31  10389.0
12  2020-12-31  10744.0
13  2020-09-30   8771.0
14  2020-06-30   6036.0
15  2020-03-31   5985.0
16  2019-12-31   7384.0
17  2019-09-30   6303.0
18  2019-06-30   6350.0
19  2019-03-31   4541.0
20  2018-12-31   7226.0
21  2018-09-30   6824.0
22  2018-06-30   4002.0
23  2018-03-31   3409.0
24  2017-12-31   3288.0
25  2017-09-30   2985.0
26  2017-06-30   2790.0
27  2017-03-31   2696.0
28  2016-12-31   2285.0
29  2016-09-30   2298.0
30  2016-06-30   1270.0
31  2016-03-31   1147.0
32  2015-12-31   1214.0
33  2015-09-30    937.0
34  2015-06-30    955.0
35  2015-03-31    940.0
36  2014-12-31    957.0
37  2014-09-30    852.0
38  2014-06-30    769.0
39  2014-03-31    621.0
40  2013-12-31    615.0
41  2013-09-30    431.0
42  2013-06-30    405.0
43  2013-03-31    562.0
44  2012-12-31    306.0
45  2012-09-30     50.0
46  2012-06-30     27.0
47  2012-03-31     30.0
48  2011-12-31     39.0
49  2011-09-30     58.0
50  2011-06-30     58.0
51  2011-03-31     49.0
52  2010-12-31     36.0
53  2010-09-30     31.0
54  2010-06-30     28.0
55  2010-03-31     21.0
56  2009-12-31      NaN
57  2009-09-30     46.0
58  2009-06-30     27.0

### 2ª Practica: Scraping Wikipedia
He probado con Wikipedia , extrayendo los datos de la tabla periodica pero no he sido capaz de limpiar el dataframe sin profundizar mas en 
Regular Expressions

In [217]:
#url del sitio a scrapear
url = 'https://es.wikipedia.org/wiki/Anexo:Elementos_qu%C3%ADmicos'
#realizamos la peticion al sitio y convertimos a texto
response = requests.get(url)
response_html = response.text
#defino condicional para manejo de excepcion
if response.status_code != 200:
    print('error al conectar')

# Creamos objeto soup
soup = bs.BeautifulSoup(response_html, 'lxml')
# Buscamos la tabla que nos interesa
table = soup.find('table', {'class': 'wikitable center'})

In [218]:
#creamos las listas donde se almacenaran cada uno de los datos de cada columna
numeros_atomicos = []
simbolos = []
elementos = []
pesos_atomicos = []
densidades = []
puntos_fusion = []
puntos_ebullicion = []
electronegatividades = []
abundancias = []
links = []

# Iteramos sobre cada fila desde el indice [2] para evitar el encabezado y una fila vacia//probramos el modulo tqdm(barra de progreso)
for row in tqdm(table.findAll('tr')[2:]):

    # Almacenamos en la variable tds todos los valores de cada fila
    tds = row.findAll('td')

    # Seleccionamos el texto de cada valor que queremos de la lista tds (los indices han sido escogidos previamente) 
    numero_atomico = tds[0].text
    simbolo = tds[1].text
    elemento = tds[2].text
    peso_atomico = tds[5].text
    densidad = tds[6].text
    fusion = tds[7].text
    ebullicion = tds[8].text
    electronegatividad = tds[10].text
    abundancia = tds[11].text
    etimologia = tds[14].text
    # Extraemos tambien el enlace al elemento 
    link = tds[2].find('a')['href'] if tds[2].find('a') else None

    # Añadimos cada valor a su respectiva lista 
    numeros_atomicos.append(numero_atomico)
    simbolos.append(simbolo)
    elementos.append(elemento)
    pesos_atomicos.append(peso_atomico)
    densidades.append(densidad)
    puntos_fusion.append(fusion)
    puntos_ebullicion.append(ebullicion)
    electronegatividades.append(electronegatividad)
    abundancias.append(abundancia)
    links.append(link)

# Ahora tenemos qeu modificar los links para incluir el dominio general ya que en la tabla solo teniamos la ruta relativa
links_completos = []
dominio = 'https://es.wikipedia.org'
# Iteramos sobre la lista conlos links
for link in links:
    # Añadimos a cada link el dominio general
    link_completo = dominio + link
    # Añadimos los links ya completados a la nueva lista [links_completos]
    links_completos.append(link_completo)

100%|██████████| 118/118 [00:00<00:00, 22564.41it/s]

In [229]:
''' UN INTENTO DE LIMPIAR LOS DATOS NUMERICOS QUE NO HA FUNCIONADO PORQUE EL PATRON NO ES CORRECTO Y ELIMINABA MUCHOS TERMINOS'''
import re
# detras de exclamacion/con o sin espacio/busca digito + decimal opcional (?:)antes de corchetes
patron = r'!\s*(\d+(?:\.\d+)?)[\[\]]'
patron2 = r'(\d+(?:\.\d+)?)'

pesoA_limpio = [re.search(patron, texto).group(1)  if re.search(patron, texto) else None for texto in pesos_atomicos]
fusion_limpio = [re.search(patron2, texto).group(1) if re.search(patron2, texto) else None for texto in puntos_fusion ]

In [228]:
# Creamos el Dataframe
data = {'Nº Atomico':numeros_atomicos,'Simbolo':simbolos,'Elemento': elementos, 'Peso Atomico':pesos_atomicos,
        'Densidad': densidades, 'P.Fusion': puntos_fusion,'P.Ebullicion':puntos_ebullicion,
        'Electronegatividad': electronegatividades, 'Abundancia':abundancias,'Enlace Web': links_completos}
df_elementos = pd.DataFrame(data)
                                                 
# Resultado
df_elementos

,Nº Atomico,Simbolo,Elemento,Peso Atomico,Densidad,P.Fusion,P.Ebullicion,Electronegatividad,Abundancia,Enlace Web
0,1,H,Hidrógeno,001 !1.008[4]​[5]​[6]​[7]​,0.00008988,14.01,20.28,2.20,1400,https://es.wikipedia.org/wiki/Hidr%C3%B3geno
1,2,He,Helio,004 !4.002602[4]​[6]​,0.0001785,0.95[8]​,4.22,–,0.008,https://es.wikipedia.org/wiki/Helio
2,3,Li,Litio,007 !6.94[4]​[5]​[6]​[9]​[7]​,0.534,453.69,1560,0.98,20,https://es.wikipedia.org/wiki/Litio
3,4,Be,Berilio,009 !9.0121831[9]​,1.85,1560,2742,1.57,2.8,https://es.wikipedia.org/wiki/Berilio
4,5,B,Boro,011 !10.81[4]​[5]​[6]​[7]​,2.34,2349,4200,2.04,10,https://es.wikipedia.org/wiki/Boro
...,...,...,...,...,...,...,...,...,...,...
113,114,Fl,Flerovio,289 ![289][13]​,14 !(14)[15]​,340 !(340)[15]​,420 !(420)[15]​,–,0 !0[14]​,https://es.wikipedia.org/wiki/Flerovio
114,115,Mc,Moscovio,289 ![289][13]​,13.5 !(13.5)[15]​,700 !(700)[15]​,1400 !(1400)[15]​,–,0 !0[14]​,https://es.wikipedia.org/wiki/Moscovio
115,116,Lv,Livermorio,293 ![293][13]​,12.9 !(12.9)[15]​,708.5 !(708.5)[15]​,1085 !(1085)[15]​,–,0 !0[14]​,https://es.wikipedia.org/wiki/Livermorio
116,117,Ts,Teneso,294 ![294][13]​,7.2 !(7.2)[15]​,723 !(723)[15]​,883 !(883)[15]​,–,0 !0[14]​,https://es.wikipedia.org/wiki/Teneso
117,118,Og,Oganesón,294 ![294][13]​,5.0 !(5.0)[15]​[17]​,258 !(258)[15]​,263 !(263)[15]​,–,0 !0[14]​,https://es.wikipedia.org/wiki/Oganes%C3%B3n